
/* This file was generated by mib2c and is intended for use as a mib module
   for the ucd-snmp snmpd agent. */

#include <config.h>

#if TIME_WITH_SYS_TIME
# include <sys/time.h>
# include <time.h>
#else
# if HAVE_SYS_TIME_H
#  include <sys/time.h>
# else
#  include <time.h>
# endif
#endif

#include "mibincl.h"
#include "snmpEngine.h"

void init_snmpEngine __P((void)) {
/* place any initialization routines needed here */
}

extern struct timeval starttime;

unsigned char *
var_snmpEngine(vp, name, length, exact, var_len, write_method)
    struct variable *vp;
    oid     *name;
    int     *length;
    int     exact;
    int     *var_len;
    int     (**write_method) __P((int, unsigned char *,unsigned char, int, unsigned char *,oid*, int));
{

  /* variables we may use later */
  static long long_ret;
  static unsigned char string[1500];
  static oid objid[30];
  static struct counter64 c64;
  struct timeval now;

  *write_method = 0;           /* assume it isnt writable for the time being */
  *var_len = sizeof(long_ret); /* assume an integer and change later if not */

  if (header_generic(vp,name,length,exact,var_len,write_method))
      return 0;

  /* this is where we do the value assignments for the mib results. */
  switch(vp->magic) {

    case SNMPENGINEID:
      *string = 0;
      *var_len = strlen(string);
      return (unsigned char *) string;

    case SNMPENGINEBOOTS:
      long_ret = snmpv3_get_engine_boots();
      return (unsigned char *) &long_ret;

    case SNMPENGINETIME:
      gettimeofday(&now, NULL);
      long_return = calculate_time_diff(now,starttime);
      return (unsigned char *) &long_ret;

    case SNMPENGINEMAXMESSAGESIZE:
      long_ret = 1500;
      return (unsigned char *) &long_ret;

    default:
      ERROR_MSG("");
  }
  return 0;
}

